#############################################################################
# Makefile for building: Red_Panda_CPP
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  Red_Panda_CPP.pro
# Template: subdirs
# Command: D:\Qt\5.15.2\msvc2019_64\bin\qmake.exe -o Makefile Red_Panda_CPP.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = D:\Qt\5.15.2\msvc2019_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\Qt\5.15.2\msvc2019_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\Qt\5.15.2\msvc2019_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-RedPandaIDE \
		sub-tools-consolepauser \
		sub-libs-redpanda_qt_utils \
		sub-libs-qsynedit \
		sub-libs-lua


sub-RedPandaIDE-qmake_all: sub-tools-consolepauser-qmake_all sub-libs-qsynedit-qmake_all sub-libs-lua-qmake_all FORCE
	@if not exist RedPandaIDE\ mkdir RedPandaIDE\ & if not exist RedPandaIDE\ exit 1
	cd RedPandaIDE\ && $(QMAKE) -o Makefile E:\RedPandaIDE\RedPandaIDE\RedPandaIDE.pro
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd RedPandaIDE\ && $(MAKE) -f Makefile qmake_all
sub-RedPandaIDE: $(MAKEFILE) sub-tools-consolepauser \
		sub-libs-qsynedit \
		sub-libs-lua FORCE
	@if not exist RedPandaIDE\ mkdir RedPandaIDE\ & if not exist RedPandaIDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd RedPandaIDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\RedPandaIDE\RedPandaIDE.pro ) && $(MAKE) -f Makefile
sub-RedPandaIDE-make_first: sub-tools-consolepauser-make_first sub-libs-qsynedit-make_first sub-libs-lua-make_first FORCE
	@if not exist RedPandaIDE\ mkdir RedPandaIDE\ & if not exist RedPandaIDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd RedPandaIDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\RedPandaIDE\RedPandaIDE.pro ) && $(MAKE) -f Makefile 
sub-RedPandaIDE-all: sub-tools-consolepauser-all sub-libs-qsynedit-all sub-libs-lua-all FORCE
	@if not exist RedPandaIDE\ mkdir RedPandaIDE\ & if not exist RedPandaIDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd RedPandaIDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\RedPandaIDE\RedPandaIDE.pro ) && $(MAKE) -f Makefile all
sub-RedPandaIDE-clean: sub-tools-consolepauser-clean sub-libs-qsynedit-clean sub-libs-lua-clean FORCE
	@if not exist RedPandaIDE\ mkdir RedPandaIDE\ & if not exist RedPandaIDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd RedPandaIDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\RedPandaIDE\RedPandaIDE.pro ) && $(MAKE) -f Makefile clean
sub-RedPandaIDE-distclean: sub-tools-consolepauser-distclean sub-libs-qsynedit-distclean sub-libs-lua-distclean FORCE
	@if not exist RedPandaIDE\ mkdir RedPandaIDE\ & if not exist RedPandaIDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd RedPandaIDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\RedPandaIDE\RedPandaIDE.pro ) && $(MAKE) -f Makefile distclean
sub-RedPandaIDE-install_subtargets: sub-tools-consolepauser-install_subtargets sub-libs-qsynedit-install_subtargets sub-libs-lua-install_subtargets FORCE
	@if not exist RedPandaIDE\ mkdir RedPandaIDE\ & if not exist RedPandaIDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd RedPandaIDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\RedPandaIDE\RedPandaIDE.pro ) && $(MAKE) -f Makefile install
sub-RedPandaIDE-uninstall_subtargets: sub-tools-consolepauser-uninstall_subtargets sub-libs-qsynedit-uninstall_subtargets sub-libs-lua-uninstall_subtargets FORCE
	@if not exist RedPandaIDE\ mkdir RedPandaIDE\ & if not exist RedPandaIDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd RedPandaIDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\RedPandaIDE\RedPandaIDE.pro ) && $(MAKE) -f Makefile uninstall
sub-tools-consolepauser-qmake_all:  FORCE
	@if not exist tools\consolepauser\ mkdir tools\consolepauser\ & if not exist tools\consolepauser\ exit 1
	cd tools\consolepauser\ && $(QMAKE) -o Makefile E:\RedPandaIDE\tools\consolepauser\consolepauser.pro
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tools\consolepauser\ && $(MAKE) -f Makefile qmake_all
sub-tools-consolepauser: $(MAKEFILE) FORCE
	@if not exist tools\consolepauser\ mkdir tools\consolepauser\ & if not exist tools\consolepauser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tools\consolepauser\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\tools\consolepauser\consolepauser.pro ) && $(MAKE) -f Makefile
sub-tools-consolepauser-make_first: FORCE
	@if not exist tools\consolepauser\ mkdir tools\consolepauser\ & if not exist tools\consolepauser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tools\consolepauser\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\tools\consolepauser\consolepauser.pro ) && $(MAKE) -f Makefile 
sub-tools-consolepauser-all: FORCE
	@if not exist tools\consolepauser\ mkdir tools\consolepauser\ & if not exist tools\consolepauser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tools\consolepauser\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\tools\consolepauser\consolepauser.pro ) && $(MAKE) -f Makefile all
sub-tools-consolepauser-clean: FORCE
	@if not exist tools\consolepauser\ mkdir tools\consolepauser\ & if not exist tools\consolepauser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tools\consolepauser\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\tools\consolepauser\consolepauser.pro ) && $(MAKE) -f Makefile clean
sub-tools-consolepauser-distclean: FORCE
	@if not exist tools\consolepauser\ mkdir tools\consolepauser\ & if not exist tools\consolepauser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tools\consolepauser\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\tools\consolepauser\consolepauser.pro ) && $(MAKE) -f Makefile distclean
sub-tools-consolepauser-install_subtargets: FORCE
	@if not exist tools\consolepauser\ mkdir tools\consolepauser\ & if not exist tools\consolepauser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tools\consolepauser\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\tools\consolepauser\consolepauser.pro ) && $(MAKE) -f Makefile install
sub-tools-consolepauser-uninstall_subtargets: FORCE
	@if not exist tools\consolepauser\ mkdir tools\consolepauser\ & if not exist tools\consolepauser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tools\consolepauser\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\tools\consolepauser\consolepauser.pro ) && $(MAKE) -f Makefile uninstall
sub-libs-redpanda_qt_utils-qmake_all:  FORCE
	@if not exist libs\redpanda_qt_utils\ mkdir libs\redpanda_qt_utils\ & if not exist libs\redpanda_qt_utils\ exit 1
	cd libs\redpanda_qt_utils\ && $(QMAKE) -o Makefile E:\RedPandaIDE\libs\redpanda_qt_utils\redpanda_qt_utils.pro
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\redpanda_qt_utils\ && $(MAKE) -f Makefile qmake_all
sub-libs-redpanda_qt_utils: $(MAKEFILE) FORCE
	@if not exist libs\redpanda_qt_utils\ mkdir libs\redpanda_qt_utils\ & if not exist libs\redpanda_qt_utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\redpanda_qt_utils\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\redpanda_qt_utils\redpanda_qt_utils.pro ) && $(MAKE) -f Makefile
sub-libs-redpanda_qt_utils-make_first: FORCE
	@if not exist libs\redpanda_qt_utils\ mkdir libs\redpanda_qt_utils\ & if not exist libs\redpanda_qt_utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\redpanda_qt_utils\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\redpanda_qt_utils\redpanda_qt_utils.pro ) && $(MAKE) -f Makefile 
sub-libs-redpanda_qt_utils-all: FORCE
	@if not exist libs\redpanda_qt_utils\ mkdir libs\redpanda_qt_utils\ & if not exist libs\redpanda_qt_utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\redpanda_qt_utils\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\redpanda_qt_utils\redpanda_qt_utils.pro ) && $(MAKE) -f Makefile all
sub-libs-redpanda_qt_utils-clean: FORCE
	@if not exist libs\redpanda_qt_utils\ mkdir libs\redpanda_qt_utils\ & if not exist libs\redpanda_qt_utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\redpanda_qt_utils\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\redpanda_qt_utils\redpanda_qt_utils.pro ) && $(MAKE) -f Makefile clean
sub-libs-redpanda_qt_utils-distclean: FORCE
	@if not exist libs\redpanda_qt_utils\ mkdir libs\redpanda_qt_utils\ & if not exist libs\redpanda_qt_utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\redpanda_qt_utils\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\redpanda_qt_utils\redpanda_qt_utils.pro ) && $(MAKE) -f Makefile distclean
sub-libs-redpanda_qt_utils-install_subtargets: FORCE
	@if not exist libs\redpanda_qt_utils\ mkdir libs\redpanda_qt_utils\ & if not exist libs\redpanda_qt_utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\redpanda_qt_utils\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\redpanda_qt_utils\redpanda_qt_utils.pro ) && $(MAKE) -f Makefile install
sub-libs-redpanda_qt_utils-uninstall_subtargets: FORCE
	@if not exist libs\redpanda_qt_utils\ mkdir libs\redpanda_qt_utils\ & if not exist libs\redpanda_qt_utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\redpanda_qt_utils\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\redpanda_qt_utils\redpanda_qt_utils.pro ) && $(MAKE) -f Makefile uninstall
sub-libs-qsynedit-qmake_all: sub-libs-redpanda_qt_utils-qmake_all FORCE
	@if not exist libs\qsynedit\ mkdir libs\qsynedit\ & if not exist libs\qsynedit\ exit 1
	cd libs\qsynedit\ && $(QMAKE) -o Makefile E:\RedPandaIDE\libs\qsynedit\qsynedit.pro
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qsynedit\ && $(MAKE) -f Makefile qmake_all
sub-libs-qsynedit: $(MAKEFILE) sub-libs-redpanda_qt_utils FORCE
	@if not exist libs\qsynedit\ mkdir libs\qsynedit\ & if not exist libs\qsynedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qsynedit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\qsynedit\qsynedit.pro ) && $(MAKE) -f Makefile
sub-libs-qsynedit-make_first: sub-libs-redpanda_qt_utils-make_first FORCE
	@if not exist libs\qsynedit\ mkdir libs\qsynedit\ & if not exist libs\qsynedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qsynedit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\qsynedit\qsynedit.pro ) && $(MAKE) -f Makefile 
sub-libs-qsynedit-all: sub-libs-redpanda_qt_utils-all FORCE
	@if not exist libs\qsynedit\ mkdir libs\qsynedit\ & if not exist libs\qsynedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qsynedit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\qsynedit\qsynedit.pro ) && $(MAKE) -f Makefile all
sub-libs-qsynedit-clean: sub-libs-redpanda_qt_utils-clean FORCE
	@if not exist libs\qsynedit\ mkdir libs\qsynedit\ & if not exist libs\qsynedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qsynedit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\qsynedit\qsynedit.pro ) && $(MAKE) -f Makefile clean
sub-libs-qsynedit-distclean: sub-libs-redpanda_qt_utils-distclean FORCE
	@if not exist libs\qsynedit\ mkdir libs\qsynedit\ & if not exist libs\qsynedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qsynedit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\qsynedit\qsynedit.pro ) && $(MAKE) -f Makefile distclean
sub-libs-qsynedit-install_subtargets: sub-libs-redpanda_qt_utils-install_subtargets FORCE
	@if not exist libs\qsynedit\ mkdir libs\qsynedit\ & if not exist libs\qsynedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qsynedit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\qsynedit\qsynedit.pro ) && $(MAKE) -f Makefile install
sub-libs-qsynedit-uninstall_subtargets: sub-libs-redpanda_qt_utils-uninstall_subtargets FORCE
	@if not exist libs\qsynedit\ mkdir libs\qsynedit\ & if not exist libs\qsynedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qsynedit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\qsynedit\qsynedit.pro ) && $(MAKE) -f Makefile uninstall
sub-libs-lua-qmake_all:  FORCE
	@if not exist libs\lua\ mkdir libs\lua\ & if not exist libs\lua\ exit 1
	cd libs\lua\ && $(QMAKE) -o Makefile E:\RedPandaIDE\libs\lua\lua.pro
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\lua\ && $(MAKE) -f Makefile qmake_all
sub-libs-lua: $(MAKEFILE) FORCE
	@if not exist libs\lua\ mkdir libs\lua\ & if not exist libs\lua\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\lua\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\lua\lua.pro ) && $(MAKE) -f Makefile
sub-libs-lua-make_first: FORCE
	@if not exist libs\lua\ mkdir libs\lua\ & if not exist libs\lua\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\lua\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\lua\lua.pro ) && $(MAKE) -f Makefile 
sub-libs-lua-all: FORCE
	@if not exist libs\lua\ mkdir libs\lua\ & if not exist libs\lua\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\lua\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\lua\lua.pro ) && $(MAKE) -f Makefile all
sub-libs-lua-clean: FORCE
	@if not exist libs\lua\ mkdir libs\lua\ & if not exist libs\lua\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\lua\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\lua\lua.pro ) && $(MAKE) -f Makefile clean
sub-libs-lua-distclean: FORCE
	@if not exist libs\lua\ mkdir libs\lua\ & if not exist libs\lua\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\lua\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\lua\lua.pro ) && $(MAKE) -f Makefile distclean
sub-libs-lua-install_subtargets: FORCE
	@if not exist libs\lua\ mkdir libs\lua\ & if not exist libs\lua\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\lua\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\lua\lua.pro ) && $(MAKE) -f Makefile install
sub-libs-lua-uninstall_subtargets: FORCE
	@if not exist libs\lua\ mkdir libs\lua\ & if not exist libs\lua\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\lua\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\lua\lua.pro ) && $(MAKE) -f Makefile uninstall

Makefile: Red_Panda_CPP.pro .qmake.conf D:\Qt\5.15.2\msvc2019_64\mkspecs\win32-msvc\qmake.conf D:\Qt\5.15.2\msvc2019_64\mkspecs\features\spec_pre.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\common\angle.conf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\common\windows-desktop.conf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\common\windows-vulkan.conf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\common\msvc-desktop.conf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\qconfig.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axbase.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_core.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designer.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_edid_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_egl_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gamepad.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gamepad_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gui.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_help.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_location.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_location_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_network.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_nfc.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_nfc_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_openglextensions.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioning.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioning_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qml.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_repparser.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_repparser_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_script.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_script_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scripttools.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scripttools_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scxml.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scxml_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sensors.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sensors_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialport.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialport_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sql.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_svg.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_theme_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_websockets.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_websockets_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webview.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webview_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_winextras.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_winextras_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xml.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\qt_functions.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\qt_config.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\win32-msvc\qmake.conf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\spec_post.prf \
		.qmake.conf \
		.qmake.stash \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\exclusive_builds.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\common\msvc-version.conf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\toolchain.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\default_pre.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\default_pre.prf \
		version.inc \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\resolve_config.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\exclusive_builds_post.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\default_post.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\precompile_header.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\warn_on.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\qmake_use.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\file_copies.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\windows.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\testcase_targets.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\exceptions.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\yacc.prf \
		D:\Qt\5.15.2\msvc2019_64\mkspecs\features\lex.prf \
		Red_Panda_CPP.pro
	$(QMAKE) -o Makefile Red_Panda_CPP.pro
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\spec_pre.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\common\angle.conf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\common\windows-desktop.conf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\common\windows-vulkan.conf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\common\msvc-desktop.conf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\qconfig.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_accessibility_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axbase.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_core.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designer.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_edid_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_egl_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gamepad.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gamepad_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gui.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_help.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_location.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_location_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_network.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_nfc.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_nfc_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_openglextensions.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioning.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioning_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qml.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_repparser.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_repparser_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_script.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_script_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scripttools.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scripttools_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scxml.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scxml_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sensors.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sensors_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialport.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialport_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sql.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_svg.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_theme_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_vulkan_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_websockets.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_websockets_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webview.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webview_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_winextras.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_winextras_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xml.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\qt_functions.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\qt_config.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\win32-msvc\qmake.conf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\spec_post.prf:
.qmake.conf:
.qmake.stash:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\exclusive_builds.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\common\msvc-version.conf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\toolchain.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\default_pre.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\default_pre.prf:
version.inc:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\resolve_config.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\exclusive_builds_post.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\default_post.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\precompile_header.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\warn_on.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\qmake_use.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\file_copies.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\windows.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\testcase_targets.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\exceptions.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\yacc.prf:
D:\Qt\5.15.2\msvc2019_64\mkspecs\features\lex.prf:
Red_Panda_CPP.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Red_Panda_CPP.pro

qmake_all: sub-RedPandaIDE-qmake_all sub-tools-consolepauser-qmake_all sub-libs-redpanda_qt_utils-qmake_all sub-libs-qsynedit-qmake_all sub-libs-lua-qmake_all FORCE

make_first: sub-RedPandaIDE-make_first sub-tools-consolepauser-make_first sub-libs-redpanda_qt_utils-make_first sub-libs-qsynedit-make_first sub-libs-lua-make_first  FORCE
all: sub-RedPandaIDE-all sub-tools-consolepauser-all sub-libs-redpanda_qt_utils-all sub-libs-qsynedit-all sub-libs-lua-all  FORCE
clean: sub-RedPandaIDE-clean sub-tools-consolepauser-clean sub-libs-redpanda_qt_utils-clean sub-libs-qsynedit-clean sub-libs-lua-clean  FORCE
distclean: sub-RedPandaIDE-distclean sub-tools-consolepauser-distclean sub-libs-redpanda_qt_utils-distclean sub-libs-qsynedit-distclean sub-libs-lua-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-RedPandaIDE-install_subtargets sub-tools-consolepauser-install_subtargets sub-libs-redpanda_qt_utils-install_subtargets sub-libs-qsynedit-install_subtargets sub-libs-lua-install_subtargets FORCE
uninstall_subtargets: sub-RedPandaIDE-uninstall_subtargets sub-tools-consolepauser-uninstall_subtargets sub-libs-redpanda_qt_utils-uninstall_subtargets sub-libs-qsynedit-uninstall_subtargets sub-libs-lua-uninstall_subtargets FORCE

sub-RedPandaIDE-debug: sub-tools-consolepauser-debug sub-libs-qsynedit-debug sub-libs-lua-debug
	@if not exist RedPandaIDE\ mkdir RedPandaIDE\ & if not exist RedPandaIDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd RedPandaIDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\RedPandaIDE\RedPandaIDE.pro ) && $(MAKE) -f Makefile debug
sub-tools-consolepauser-debug:
	@if not exist tools\consolepauser\ mkdir tools\consolepauser\ & if not exist tools\consolepauser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tools\consolepauser\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\tools\consolepauser\consolepauser.pro ) && $(MAKE) -f Makefile debug
sub-libs-redpanda_qt_utils-debug:
	@if not exist libs\redpanda_qt_utils\ mkdir libs\redpanda_qt_utils\ & if not exist libs\redpanda_qt_utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\redpanda_qt_utils\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\redpanda_qt_utils\redpanda_qt_utils.pro ) && $(MAKE) -f Makefile debug
sub-libs-qsynedit-debug: sub-libs-redpanda_qt_utils-debug
	@if not exist libs\qsynedit\ mkdir libs\qsynedit\ & if not exist libs\qsynedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qsynedit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\qsynedit\qsynedit.pro ) && $(MAKE) -f Makefile debug
sub-libs-lua-debug:
	@if not exist libs\lua\ mkdir libs\lua\ & if not exist libs\lua\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\lua\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\lua\lua.pro ) && $(MAKE) -f Makefile debug
debug: sub-RedPandaIDE-debug sub-tools-consolepauser-debug sub-libs-redpanda_qt_utils-debug sub-libs-qsynedit-debug sub-libs-lua-debug

sub-RedPandaIDE-release: sub-tools-consolepauser-release sub-libs-qsynedit-release sub-libs-lua-release
	@if not exist RedPandaIDE\ mkdir RedPandaIDE\ & if not exist RedPandaIDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd RedPandaIDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\RedPandaIDE\RedPandaIDE.pro ) && $(MAKE) -f Makefile release
sub-tools-consolepauser-release:
	@if not exist tools\consolepauser\ mkdir tools\consolepauser\ & if not exist tools\consolepauser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tools\consolepauser\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\tools\consolepauser\consolepauser.pro ) && $(MAKE) -f Makefile release
sub-libs-redpanda_qt_utils-release:
	@if not exist libs\redpanda_qt_utils\ mkdir libs\redpanda_qt_utils\ & if not exist libs\redpanda_qt_utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\redpanda_qt_utils\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\redpanda_qt_utils\redpanda_qt_utils.pro ) && $(MAKE) -f Makefile release
sub-libs-qsynedit-release: sub-libs-redpanda_qt_utils-release
	@if not exist libs\qsynedit\ mkdir libs\qsynedit\ & if not exist libs\qsynedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qsynedit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\qsynedit\qsynedit.pro ) && $(MAKE) -f Makefile release
sub-libs-lua-release:
	@if not exist libs\lua\ mkdir libs\lua\ & if not exist libs\lua\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\lua\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\lua\lua.pro ) && $(MAKE) -f Makefile release
release: sub-RedPandaIDE-release sub-tools-consolepauser-release sub-libs-redpanda_qt_utils-release sub-libs-qsynedit-release sub-libs-lua-release

sub-RedPandaIDE-check: sub-tools-consolepauser-check sub-libs-qsynedit-check sub-libs-lua-check
	@if not exist RedPandaIDE\ mkdir RedPandaIDE\ & if not exist RedPandaIDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd RedPandaIDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\RedPandaIDE\RedPandaIDE.pro ) && $(MAKE) -f Makefile check
sub-tools-consolepauser-check:
	@if not exist tools\consolepauser\ mkdir tools\consolepauser\ & if not exist tools\consolepauser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tools\consolepauser\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\tools\consolepauser\consolepauser.pro ) && $(MAKE) -f Makefile check
sub-libs-redpanda_qt_utils-check:
	@if not exist libs\redpanda_qt_utils\ mkdir libs\redpanda_qt_utils\ & if not exist libs\redpanda_qt_utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\redpanda_qt_utils\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\redpanda_qt_utils\redpanda_qt_utils.pro ) && $(MAKE) -f Makefile check
sub-libs-qsynedit-check: sub-libs-redpanda_qt_utils-check
	@if not exist libs\qsynedit\ mkdir libs\qsynedit\ & if not exist libs\qsynedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qsynedit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\qsynedit\qsynedit.pro ) && $(MAKE) -f Makefile check
sub-libs-lua-check:
	@if not exist libs\lua\ mkdir libs\lua\ & if not exist libs\lua\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\lua\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\lua\lua.pro ) && $(MAKE) -f Makefile check
check: sub-RedPandaIDE-check sub-tools-consolepauser-check sub-libs-redpanda_qt_utils-check sub-libs-qsynedit-check sub-libs-lua-check

sub-RedPandaIDE-benchmark: sub-tools-consolepauser-benchmark sub-libs-qsynedit-benchmark sub-libs-lua-benchmark
	@if not exist RedPandaIDE\ mkdir RedPandaIDE\ & if not exist RedPandaIDE\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd RedPandaIDE\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\RedPandaIDE\RedPandaIDE.pro ) && $(MAKE) -f Makefile benchmark
sub-tools-consolepauser-benchmark:
	@if not exist tools\consolepauser\ mkdir tools\consolepauser\ & if not exist tools\consolepauser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tools\consolepauser\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\tools\consolepauser\consolepauser.pro ) && $(MAKE) -f Makefile benchmark
sub-libs-redpanda_qt_utils-benchmark:
	@if not exist libs\redpanda_qt_utils\ mkdir libs\redpanda_qt_utils\ & if not exist libs\redpanda_qt_utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\redpanda_qt_utils\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\redpanda_qt_utils\redpanda_qt_utils.pro ) && $(MAKE) -f Makefile benchmark
sub-libs-qsynedit-benchmark: sub-libs-redpanda_qt_utils-benchmark
	@if not exist libs\qsynedit\ mkdir libs\qsynedit\ & if not exist libs\qsynedit\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\qsynedit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\qsynedit\qsynedit.pro ) && $(MAKE) -f Makefile benchmark
sub-libs-lua-benchmark:
	@if not exist libs\lua\ mkdir libs\lua\ & if not exist libs\lua\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd libs\lua\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\RedPandaIDE\libs\lua\lua.pro ) && $(MAKE) -f Makefile benchmark
benchmark: sub-RedPandaIDE-benchmark sub-tools-consolepauser-benchmark sub-libs-redpanda_qt_utils-benchmark sub-libs-qsynedit-benchmark sub-libs-lua-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

