#ifndef ZIPUNPACKER_GLOBAL_H
#define ZIPUNPACKER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ZIPUNPACKER_LIBRARY)
#  define ZIPUNPACKERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ZIPUNPACKERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ZIPUNPACKER_GLOBAL_H
