name: Build with MSVC2022

on:
  # push:
  #   paths-ignore:
  #     - ".github/**"
  #     - ".gitignore"
  #     - ".gitattributes"
  #     - "**.md"
  #     - "LICENSE"
  # pull_request:
  #   paths-ignore:
  #     - ".github/**"
  #     - ".gitignore"
  #     - ".gitattributes"
  #     - "**.md"
  #     - "LICENSE"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        arch: [x64] #, x86, arm64]  # 可扩展为x86、arm64等架构
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install Qt 6.9.1
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.0'
        host: windows
        target: desktop
        arch: win64_msvc2022_64
        archives: qtbase qtsvg qttools
        tools: tools_qtcreator,qt.tools.qtcreator

    - name: Install dependencies
      run: |
        choco install -y nsis 7zip git curl cmake
        choco install -y visualstudio2022-buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.MSBuildTools --add Microsoft.VisualStudio.Workload.VCTools --quiet"
        refreshenv
      shell: cmd

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build application
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        .\packages\build.bat --mingw64 --target-dir "%GITHUB_WORKSPACE%\dist"
      shell: cmd

    - name: Upload setup package
      uses: actions/upload-artifact@v4
      with:
        name: redpanda-setup-${{ matrix.arch }}
        path: ${{ github.workspace }}/dist/*.exe

    - name: Upload portable package
      uses: actions/upload-artifact@v4
      with:
        name: redpanda-portable-${{ matrix.arch }}
        path: ${{ github.workspace }}/dist/*.7z
